<a href="https://colab.research.google.com/github/PrishaAggarwal/Machine_Learning_Assignments/blob/main/ML_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#Assignment_1
# !pip install numpy (for jupyter notebook)
import numpy as np

In [ ]:
#Q1
#part a
arr = np.array([1,2,3,6,4,5])
arr_reversed = arr[::-1]
print(arr_reversed)

[5 4 6 3 2 1]


In [ ]:
#Q1
#part b
array1 = np.array([[1,2,3],[2,4,5],[1,2,3]])
flat1 = array1.flatten()
print(flat1)

flat2 = array1.reshape(-1)
#1,-1 se u will get 2d array with 1 row and 6 columns jabki we want 1d array here
print(flat2)

[1 2 3 2 4 5 1 2 3]
[1 2 3 2 4 5 1 2 3]


In [ ]:
#Q1
#part c
arr1 = np.array([[1,2],[3,4]])
arr2 = np.array([[1,2],[3,4]])
if (arr1==arr2).all():
  print('same')
else:
  print('not same')

#another method
if np.array_equal(arr1, arr2):
    print("same")
else:
    print("not same")


same
same


In [ ]:
#Q1
#part d
x = np.array([1,2,3,4,5,1,2,1,1,1])
y = np.array([1,1,1,2,3,4,2,4,3,3])

values,counts = np.unique(x,return_counts=True)
most_freq = values[counts.argmax()]
# np.argmax(counts) gives max count wala index
#counts.argmax() since it gives the index of largest count..i.e largest number in count array mein..oska index we get
index = np.where(x==most_freq)[0]
#np.where....this returns the tuple of indices where the condition is true
#[0] used why ??
# np.where returns a tuple of arrays, one array for each dimension fo your input
#[0] nhi lagate then aata ([0,5,7,8,9]),)
#we dont want the array in tuple and we just want 1st element of tuple so we use [0]
print("Most frequent value:", most_freq)
print("Indices:", index)

Most frequent value: 1
Indices: [0 5 7 8 9]


In [ ]:
#Q1
#part e
gfg = np.matrix('[4,1,9;12,3,1;4,5,6]')
#np.matrix creates a matrix object
#upar wale tarike se we used phele but aab we use .array[[],[],[]]

#sum of all elements
sum_all = gfg.sum()
print(sum_all)

#Sum of all elements row-wise
sum_row = gfg.sum(axis=0)
print(sum)

#Sum of all elements column-wise
sum_col = gfg.sum(axis=1)
print(sum_col)

45
<built-in function sum>
[[14]
 [16]
 [15]]


In [ ]:
#Q1
#part f
n_array=np.array([[55,25,15],[30,44,2],[11,45,77]])

#sum of diagonal elements
diagonal1 = np.trace(n_array)
print(diagonal1)

diagonal2 = np.diag(n_array).sum()
print(diagonal2)

#eigen values and eigen vectors of matrix
#linalg is linear algebra module in numpy
vals, vecs = np.linalg.eig(n_array)
print(vals)
print(vecs)

#Inverse of matrix
inv = np.linalg.inv(n_array)
print(inv)

#Determinant of matrix
deter = np.linalg.det(n_array)
print(deter)

176
176
[98.16835147 28.097044   49.73460452]
[[ 0.4574917   0.34637121 -0.15017693]
 [ 0.28447814 -0.72784061 -0.4852124 ]
 [ 0.84248058  0.59184038  0.8614034 ]]
[[ 0.02404141 -0.00911212 -0.00444671]
 [-0.01667882  0.02966905  0.0024785 ]
 [ 0.00631287 -0.01603732  0.01217379]]
137180.0000000001


In [ ]:
#Q1
#part g

#part i
p=[[1,2],[2,3]]
q=[[4,5],[6,7]]

multiply1 = np.dot(p,q)
#for covariance u directly cant use matrices
#first u have to convert them into 1d array and find covarince
#co variance is how 2 variables change together
x=np.array(p)
y=np.array(q)

x_flat = x.flatten()
y_flat = y.flatten()
coovarince1 = np.cov(x_flat,y_flat)

print(multiply1,coovarince1)

#part ii
p1=[[1,2],[2,3],[4,5]]
q1=[[4,5,1],[6,7,2]]

multiply2 = np.dot(p1,q1)

x1=np.array(p1)
y1=np.array(q1)

x1_flat = x1.flatten()
y1_flat = y1.flatten()
coovarince2 = np.cov(x1_flat,y1_flat)

print(multiply2,coovarince2)

[[16 19]
 [26 31]] [[0.66666667 1.        ]
 [1.         1.66666667]]
[[16 19  5]
 [26 31  8]
 [46 55 14]] [[2.16666667 0.23333333]
 [0.23333333 5.36666667]]


In [ ]:
#Q1
#part h
x = np.array([[2, 3, 4], [3, 2, 9]])
y = np.array([[1, 5, 0], [5, 10, 3]])

#For matrices: the “inner product” is often used to mean matrix multiplication (when dimensions align).
# A(2x3) x B(3x2) = C(2x2)
inner = np.inner(x,y)
print(inner)

#outer cartesian product means element wise multiplication i.e each element of matrix 1 is multiplied by corresponding element of matrix 2
#matrix size can be diff
#here axb = a x b transpose
#basically a = [1,2] , b=[3,4,5]
# step 1 : Take the first element of 𝑎(which is 1) and multiply with all of b
# we get [3,4,5]
#step 2 : Take the second element of a(which is 2) and multiply with all of b
# we get [6,8,10]
#step 3 : stack them as rows and we get the answer
outer = np.outer(x,y)
print(outer)


#cartesian product : set of all ordered pairs between elements of two sets (not really a matrix operation).
#it comes from set theory
from itertools import product #intertools gives tools for creating iterators i.e things u can loop over
cartesian = np.array(list(product(x.flatten(),y.flatten())))
#after using product we get tuples like (1,3) (1,4) (2,3) (2,4)
#now we want all tuples at once so we convert them into list [(1,3),(1,4),(2,3),(2,4)]
#then we convert into arrays to make it a matrix
print(cartesian)

[[17 52]
 [13 62]]
[[ 2 10  0 10 20  6]
 [ 3 15  0 15 30  9]
 [ 4 20  0 20 40 12]
 [ 3 15  0 15 30  9]
 [ 2 10  0 10 20  6]
 [ 9 45  0 45 90 27]]
[[ 2  1]
 [ 2  5]
 [ 2  0]
 [ 2  5]
 [ 2 10]
 [ 2  3]
 [ 3  1]
 [ 3  5]
 [ 3  0]
 [ 3  5]
 [ 3 10]
 [ 3  3]
 [ 4  1]
 [ 4  5]
 [ 4  0]
 [ 4  5]
 [ 4 10]
 [ 4  3]
 [ 3  1]
 [ 3  5]
 [ 3  0]
 [ 3  5]
 [ 3 10]
 [ 3  3]
 [ 2  1]
 [ 2  5]
 [ 2  0]
 [ 2  5]
 [ 2 10]
 [ 2  3]
 [ 9  1]
 [ 9  5]
 [ 9  0]
 [ 9  5]
 [ 9 10]
 [ 9  3]]


In [ ]:
#Q2
#part a
#part i

n = np.array([[1,-2,3],[-4,5,-5]])
abs1 = np.abs(n)
print(abs1)

#part ii
#percentile of flattened array
flat_percentile = np.percentile(n,[25,50,75])
print(flat_percentile)

#percentile column wise
col_percentile = np.percentile(n,[25,50,75],axis=0)
print(col_percentile)
#ismein row 1 = 25th percentile of each column
# row 2 = 50th percentile of each column
# row 3 = 75th percentile of each column

#percentile row wise
row_percentile = np.percentile(n,[25,50,75],axis=1)
print(row_percentile)
#number of rows = number of percentile u asked for
#number of columns = number of rows in your matrix
#column 1 = percentiles for row 1 ([10,20,30])
#column 2 = percentiles for row 2 ([40,50,60])

[[1 2 3]
 [4 5 5]]
[-3.5 -0.5  2.5]
[[-2.75 -0.25 -3.  ]
 [-1.5   1.5  -1.  ]
 [-0.25  3.25  1.  ]]
[[-0.5 -4.5]
 [ 1.  -4. ]
 [ 2.   0.5]]


In [ ]:
#Q2
#part a
#part iii

#mean,median,sd of flattened array
#without flattening if we apply these functions then voh directly flat krke operations lagata hai
flat_mean = np.mean(n)
flat_median = np.median(n)
flat_sd = np.std(n)
print(flat_mean,flat_median,flat_sd)

#row wise
row_mean = np.mean(n,axis=1)
row_median = np.median(n,axis=1)
row_sd = np.std(n,axis=1)
print(row_mean,row_median,row_sd)
#jo phela [0.6667 -1.3333] yeh row wise mean hai
#2nd wala median
#3rd wala sd

#column wise
col_mean = np.mean(n,axis=0)
col_median = np.median(n,axis=0)
col_sd = np.std(n,axis=0)
print(col_mean,col_median,col_sd)

-0.3333333333333333 -0.5 3.636237371545238
[ 0.66666667 -1.33333333] [ 1. -4.] [2.05480467 4.49691252]
[-1.5  1.5 -1. ] [-1.5  1.5 -1. ] [2.5 3.5 4. ]


In [ ]:
#Q2
#part b

a = np.array([-1.8, -1.6, -0.5, 0.5, 1.6, 1.8, 3.0])

floor = np.floor(a)
ceiling = np.ceil(a)
trunc = np.trunc(a)
round = np.round(a)

print(floor,ceiling,trunc,round)

[-2. -2. -1.  0.  1.  1.  3.] [-1. -1. -0.  1.  2.  2.  3.] [-1. -1. -0.  0.  1.  1.  3.] [-2. -2. -0.  0.  2.  2.  3.]


In [ ]:
#Q3
#part a

b = np.array([-1.8, -1.6, -0.5, 0.5,1.6, 1.8, 3.0])

sort = np.sort(b)
index = np.argsort(b)
#first flatten the array if 2d and then find largest and smallest elements
smallest_4 = sort[0:4] #ending wala not counted i.e 4th element not printed
largest_5 = sort[-5:] #humne piche se 5th element se lekr end tak print krna hai

print(sort,index,smallest_4,largest_5)

[-1.8 -1.6 -0.5  0.5  1.6  1.8  3. ] [0 1 2 3 4 5 6] [-1.8 -1.6 -0.5  0.5] [-0.5  0.5  1.6  1.8  3. ]


In [ ]:
#Q3
#part b

c = np.array([1.0, 1.2, 2.2, 2.0, 3.0, 2.0])

#here we will use %,==,!= all of which are vectorized operations
integers = (c % 1 == 0)
floats = ( c % 1 != 0)
#so upar se boolean wali array is ready
#numpy lets you index an array with boolean mask

int_num = c[integers]
float_num = c[floats]

print(int_num,float_num)

[1. 2. 3. 2.] [1.2 2.2]


In [ ]:
#Q4
#part a

#!pip install cv2 (for jupyter notebook)
import cv2

def img_to_array(path):
  img = cv2.imread(path,cv2.IMREAD_UNCHANGED)
# keeps the image in the format given rgb or grayscale
  if img is None:
    print("Error")
    return

  if len(img.shape) == 2:
    print("Grayscale")
    arr = np.array(img)
    np.savetxt("Grayscale_image.txt",arr,fmt="%d")
    #fmt is format string i.e it controls how number in the array is written into text file
    # %d means save as integer

  elif len(img.shape) == 3 and img.shape[2] == 3:
    print("RGB")
    arr = np.array(img)
    with open("RGB_image.txt","w") as f:
      #f is file object
      #with isliye written taki file is automatically closed after writing
      for channel,color in zip(range(3),["R","G","B"]):
        #so range 2 means 0 for r
        # 1 for g
        # 2 for b
        # zip pairs numbers and channels like (0,"R") (1,"G") (2,"B")
        # on each loop channel gets number 0,1,2
        # color gets corresponding label
        f.write(f"\n{color} channel:\n") # f is formated string
        #\n means new line
        np.savetxt(f,arr[:,:,channel],fmt="%d")
        # [:,:,channel] selects one channel of rgb in 1st iteration
        # then all those pixels are converted into grayscale intensity values for that channel in form of 2d matrix
        # similarly in next iteration other channel are appended in same file
  else:
    print("Unsupported")

  print("Array saved")

img_to_array("/mountains_ML.jpeg")

RGB
Array saved


In [ ]:
#Q4
#part b

#gray_arr = np.loadtxt("Grayscale_image.txt", dtype=int)
#print(gray_arr.shape)
#print(gray_arr)

def load_saved_file(filename):
    try:
        if filename == "Grayscale_image.txt":
            arr = np.loadtxt(filename, dtype=int)
            print("Loaded grayscale array of shape:", arr.shape)
            return arr
        elif filename == "RGB_image.txt":
            with open(filename, "r") as f:
                content = f.read()
            print("Loaded RGB data as text.")
            return content
        else:
            print("Unknown file type")
            return None
    except FileNotFoundError:
        print(f"{filename} not found")
        return None


# Example Usage
saved_file = img_to_array("/Gray_ML.webp")
data = load_saved_file(saved_file)

RGB
Array saved
Unknown file type
